// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230419094440_Extended_Perpretator_Limit_Increase")]
    partial class Extended_Perpretator_Limit_Increase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LocalGovernmentAreaId")
                        .HasColumnType("int");

                    b.Property<string>("LocalGovernmentAreas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasMaxLength(27)
                        .HasColumnType("nvarchar(27)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Code"), false);

                    b.HasIndex("CreatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAt"), false);

                    b.HasIndex("Designation");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Designation"), false);

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Email"), false);

                    b.HasIndex("LocalGovernmentAreaId");

                    b.HasIndex("ModifiedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ModifiedAt"), false);

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("StateId");

                    b.HasIndex("Type");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Type"), false);

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ActualLocationOfIncident")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActualReferralServiceReceived")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AgeOfSurvior")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CanBeEdited")
                        .HasColumnType("bit");

                    b.Property<string>("CaseCategories")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("CaseCategoriesOthers")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int?>("CaseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CaseClosedDate")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactChannel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactChannelOrganisation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactChannelOrganisationIncidentCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ContactChannelOrganisationService")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateJusticeReceived")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfIncident")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReported")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("DoesSurviorLiveAlone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DoestheSurviorWantJustice")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Education")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmploymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmploymentStatusOfParentOrGuardian")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FollowUpActionByCSO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GBV_COVID19_Question1")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("GBV_COVID19_Question2")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("GBV_COVID19_Question3")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GBV_COVID19_Question4")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("HasCaseBeenClosed")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("HasSurviorReceivedService")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("IncidentCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("IncidentLGAId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentStateId")
                        .HasColumnType("int");

                    b.Property<int?>("IncidentWardId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("IsSurviorContinuousThreat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LgaValidated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LgaValidatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("LgaValidatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOfServiceProviderReferredTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NumberOfPerpetrators")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganisationLgaId")
                        .HasColumnType("int");

                    b.Property<string>("OtherServiceProviderAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OtherServiceProviderIncidentCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OtherServiceProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OutcomeOfProsecution")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("OutcomeOfServiceorReferral")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PerpetratorsInformation")
                        .HasMaxLength(5000000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivingOrganisationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferralOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SerialNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("SexOfSurvior")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SurviorDoesNotWantJusticeReasons")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SurvivorEstimatedAverageMonthlyIncome")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SurvivorMobileNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TypeOfReferralServiceRequired")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TypeOfServiceProvidedToSurvior")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TypeOfServiceReceivedBySurvior")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VulnerablePopulation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WasViolenceFatal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("WhoClosedTheCase")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("WhoDoesSurviorLiveWith")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("WhoReportedIncident")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ApprovedAt"), false);

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CaseCategoryId");

                    b.HasIndex("CreatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAt"), false);

                    b.HasIndex("CreatedById");

                    b.HasIndex("DateOfIncident");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("DateOfIncident"), false);

                    b.HasIndex("DateReported");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("DateReported"), false);

                    b.HasIndex("HasCaseBeenClosed");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("HasCaseBeenClosed"), false);

                    b.HasIndex("IncidentCode")
                        .IsUnique()
                        .HasFilter("[IncidentCode] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("IncidentCode"), false);

                    b.HasIndex("IncidentLGAId");

                    b.HasIndex("IncidentStateId");

                    b.HasIndex("IncidentWardId");

                    b.HasIndex("LgaValidatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("LgaValidatedAt"), false);

                    b.HasIndex("LgaValidatedById");

                    b.HasIndex("ModifiedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ModifiedAt"), false);

                    b.HasIndex("OrganisationId");

                    b.HasIndex("SerialNumber");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SerialNumber"), false);

                    b.HasIndex("SexOfSurvior");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SexOfSurvior"), false);

                    b.HasIndex("TimeOfDay");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("TimeOfDay"), false);

                    b.HasIndex("ValidatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ValidatedAt"), false);

                    b.HasIndex("ValidatedById");

                    b.HasIndex("VulnerablePopulation");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("VulnerablePopulation"), false);

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("Core.Entities.CaseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaseCategories");
                });

            modelBuilder.Entity("Core.Entities.ComplaintForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ComplaintCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ComplaintType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("ComplaintForms");
                });

            modelBuilder.Entity("Core.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Core.Entities.FileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ComplaintFormId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnExternalStorage")
                        .HasColumnType("bit");

                    b.Property<string>("MetaData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintFormId");

                    b.HasIndex("CreatedById");

                    b.ToTable("FilesUploads");
                });

            modelBuilder.Entity("Core.Entities.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CaseClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FinalOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasCaseBeenClosed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasClientReceivedjustice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JusticeReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("WhoClosedTheCase")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("CreatedById");

                    b.ToTable("FollowUps");
                });

            modelBuilder.Entity("Core.Entities.LocalGovernmentArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("LocalGovernmentAreas");
                });

            modelBuilder.Entity("Core.Entities.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganisationType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialMediaData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("States")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Code"), false);

                    b.HasIndex("CreatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAt"), false);

                    b.HasIndex("ModifiedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ModifiedAt"), false);

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Name"), false);

                    b.HasIndex("OrganisationType");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("OrganisationType"), false);

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Core.Entities.ServiceProvided", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgeOfSurvivorInYears")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateOfServiceProvision")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("GbvCovid19Question1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GbvCovid19Question2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GbvCovid19Question3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GbvCovid19Question4")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HasSurvivorReceivedServiceFromAnotherOrganisation")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("IncidentCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IncidentCodeFromReferringOrganisation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOfServiceProviderOrCsoReferredTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganisationLgaId")
                        .HasColumnType("int");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReferralOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferralToAnotherCsoOrSPcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SerialNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("ServiceProvisionCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SexOfSurvivorOrVictim")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SpOrCsoApprovalById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SpOrCsoApprovalDate")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("StateApprovalById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StateApprovalDate")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("TypeOfClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeOfServiceNeeded")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TypeOfServiceProvided")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TypeOfServiceReceivedAnotherOrganisation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TypeOfServiceReferredFor")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAt"), false);

                    b.HasIndex("CreatedById");

                    b.HasIndex("IncidentCode");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("IncidentCode"), false);

                    b.HasIndex("ModifiedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ModifiedAt"), false);

                    b.HasIndex("OrganisationId");

                    b.HasIndex("ServiceProvisionCode")
                        .IsUnique()
                        .HasFilter("[ServiceProvisionCode] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ServiceProvisionCode"), false);

                    b.HasIndex("SexOfSurvivorOrVictim");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SexOfSurvivorOrVictim"), false);

                    b.HasIndex("SpOrCsoApprovalById");

                    b.HasIndex("StateApprovalById");

                    b.HasIndex("StateId");

                    b.ToTable("ServicesProvided");
                });

            modelBuilder.Entity("Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AllowPrevMonthCases")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasDateReportedValidation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGBVQuestionsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Core.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Core.Entities.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalGovernmentAreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasMaxLength(27)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocalGovernmentAreaId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Core.Entities.LocalGovernmentArea", "LocalGovernmentArea")
                        .WithMany("Users")
                        .HasForeignKey("LocalGovernmentAreaId");

                    b.HasOne("Core.Entities.Organisation", "Organisation")
                        .WithMany("Users")
                        .HasForeignKey("OrganisationId");

                    b.HasOne("Core.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("LocalGovernmentArea");

                    b.Navigation("Organisation");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Core.Entities.Case", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", "ApprovedBy")
                        .WithMany("ApprovedCases")
                        .HasForeignKey("ApprovedById");

                    b.HasOne("Core.Entities.CaseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CaseCategoryId");

                    b.HasOne("Core.Entities.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedCases")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Core.Entities.LocalGovernmentArea", "IncidentLGA")
                        .WithMany()
                        .HasForeignKey("IncidentLGAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.State", "IncidentState")
                        .WithMany()
                        .HasForeignKey("IncidentStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Ward", "IncidentWard")
                        .WithMany()
                        .HasForeignKey("IncidentWardId");

                    b.HasOne("Core.Entities.ApplicationUser", "LgaValidatedBy")
                        .WithMany()
                        .HasForeignKey("LgaValidatedById");

                    b.HasOne("Core.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ApplicationUser", "ValidatedBy")
                        .WithMany("ValidatedCases")
                        .HasForeignKey("ValidatedById");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("IncidentLGA");

                    b.Navigation("IncidentState");

                    b.Navigation("IncidentWard");

                    b.Navigation("LgaValidatedBy");

                    b.Navigation("Organisation");

                    b.Navigation("ValidatedBy");
                });

            modelBuilder.Entity("Core.Entities.ComplaintForm", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId");

                    b.HasOne("Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.FileUpload", b =>
                {
                    b.HasOne("Core.Entities.ComplaintForm", null)
                        .WithMany("Attachements")
                        .HasForeignKey("ComplaintFormId");

                    b.HasOne("Core.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Core.Entities.FollowUp", b =>
                {
                    b.HasOne("Core.Entities.Case", "Case")
                        .WithMany("FollowUpActions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("Case");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Core.Entities.LocalGovernmentArea", b =>
                {
                    b.HasOne("Core.Entities.State", "State")
                        .WithMany("LocalGovernmentAreas")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Core.Entities.ServiceProvided", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Core.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ApplicationUser", "SpOrCsoApprovalBy")
                        .WithMany()
                        .HasForeignKey("SpOrCsoApprovalById");

                    b.HasOne("Core.Entities.ApplicationUser", "StateApprovalBy")
                        .WithMany()
                        .HasForeignKey("StateApprovalById");

                    b.HasOne("Core.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Organisation");

                    b.Navigation("SpOrCsoApprovalBy");

                    b.Navigation("State");

                    b.Navigation("StateApprovalBy");
                });

            modelBuilder.Entity("Core.Entities.Ward", b =>
                {
                    b.HasOne("Core.Entities.LocalGovernmentArea", "LocalGovernmentArea")
                        .WithMany("Wards")
                        .HasForeignKey("LocalGovernmentAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalGovernmentArea");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ApprovedCases");

                    b.Navigation("CreatedCases");

                    b.Navigation("ValidatedCases");
                });

            modelBuilder.Entity("Core.Entities.Case", b =>
                {
                    b.Navigation("FollowUpActions");
                });

            modelBuilder.Entity("Core.Entities.ComplaintForm", b =>
                {
                    b.Navigation("Attachements");
                });

            modelBuilder.Entity("Core.Entities.LocalGovernmentArea", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Core.Entities.Organisation", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Entities.State", b =>
                {
                    b.Navigation("LocalGovernmentAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
